import { NextResponse } from "next/server";
import { prisma } from "@/lib/prisma";

export const dynamic = "force-dynamic";

export async function POST(request: Request) {
  try {
    const apiKey = process.env.GROQ_API_KEY;
    const fallbackApiKey = process.env.GROQ_API_KEY_FALLBACK;
    const model = process.env.GROQ_MODEL || "llama-3.1-8b-instant";

    if (!apiKey && !fallbackApiKey) {
      return NextResponse.json(
        {
          success: false,
          error: "Groq API key not configured on server.",
        },
        { status: 500 }
      );
    }

    const { prompt, projects, assignees, customCategories, workspaceId, userName, userEmail } = await request.json();

    if (!prompt || typeof prompt !== "string") {
      return NextResponse.json(
        {
          success: false,
          error: "Prompt is required.",
        },
        { status: 400 }
      );
    }

    const categories = Array.from(
      new Set(["General", "Product", "Engineering", "Design", "Operations", "Marketing", ...(customCategories || [])])
    );

    // Minimize tokens by trimming objects to only required keys
    const cleanProjects = (projects || []).map((p: any) => ({
      id: p.id,
      name: p.name,
    }));
    
    const cleanAssignees = (assignees || []).filter((a: string) => a !== "Unassigned");

    const todayStr = new Date().toLocaleDateString("en-US", {
      weekday: "long",
      year: "numeric",
      month: "long",
      day: "numeric",
    });

    const systemPrompt = `You are a parser. Extract task fields from prompt into JSON.
Today's Date: ${todayStr}

Projects: ${JSON.stringify(cleanProjects)}
Assignees: ${JSON.stringify(cleanAssignees)}
Categories: ${JSON.stringify(categories)}

JSON Schema:
{
  "title": "Clean, concise task title.",
  "description": "Generate a detailed task description based on the prompt. List standard bullet steps or guidelines relevant to the prompt context. Add \\n\\n(Generated by ANSH Copilot) at the end.",
  "priority": "low"|"medium"|"high"|"urgent",
  "status": "todo"|"in_progress"|"review"|"blocked"|"on_hold"|"done",
  "category": "Matching category or General",
  "assignees": ["Full matching name from Assignees list"],
  "projectId": "Matching project ID or null",
  "dueLabel": "Format as 'YYYY-MM-DD' (e.g. '2026-07-19') if a relative or absolute date is mentioned (e.g., 'tomorrow', 'next Monday', '25th July'). Use Today's Date to calculate it. If no date is mentioned, set to 'No date'.",
  "labels": ["Bug"|"Feature"|"Improvement"|"Docs"|"Design"|"Meeting"]
}

Return ONLY valid JSON. No markdown wrappers or explanation.`;

    const requestBody = {
      model: model,
      messages: [
        { role: "system", content: systemPrompt },
        { role: "user", content: `Prompt: "${prompt}"` },
      ],
      temperature: 0.15,
      max_tokens: 500,
      response_format: { type: "json_object" },
    };

    let groqResponse: Response | null = null;

    try {
      // Try primary API Key if available
      if (apiKey) {
        groqResponse = await fetch("https://api.groq.com/openai/v1/chat/completions", {
          method: "POST",
          headers: {
            "Content-Type": "application/json",
            Authorization: `Bearer ${apiKey}`,
          },
          body: JSON.stringify(requestBody),
        });
      }

      // If primary key is unavailable, or failed (e.g. rate limit / limit exceeded), try fallback key
      if ((!groqResponse || !groqResponse.ok) && fallbackApiKey) {
        if (groqResponse) {
          console.warn(`Primary Groq API key failed (status: ${groqResponse.status}). Trying fallback API key...`);
        } else {
          console.log("Primary API key not available, using fallback API key...");
        }
        groqResponse = await fetch("https://api.groq.com/openai/v1/chat/completions", {
          method: "POST",
          headers: {
            "Content-Type": "application/json",
            Authorization: `Bearer ${fallbackApiKey}`,
          },
          body: JSON.stringify(requestBody),
        });
      }
    } catch (err) {
      console.error("Exception during primary Groq request:", err);
      if (fallbackApiKey) {
        console.log("Trying fallback Groq API key after exception...");
        groqResponse = await fetch("https://api.groq.com/openai/v1/chat/completions", {
          method: "POST",
          headers: {
            "Content-Type": "application/json",
            Authorization: `Bearer ${fallbackApiKey}`,
          },
          body: JSON.stringify(requestBody),
        });
      } else {
        throw err;
      }
    }

    if (!groqResponse || !groqResponse.ok) {
      const errStatus = groqResponse ? groqResponse.status : "unknown";
      const errText = groqResponse ? await groqResponse.text() : "No response";
      console.error(`Groq API returned error status ${errStatus}:`, errText);
      return NextResponse.json(
        {
          success: false,
          error: "Failed to communicate with Groq AI API.",
        },
        { status: 502 }
      );
    }

    const data = await groqResponse.json();
    const resultText = data.choices?.[0]?.message?.content;

    if (!resultText) {
      return NextResponse.json(
        {
          success: false,
          error: "No parsed response returned from Groq AI API.",
        },
        { status: 502 }
      );
    }

    const parsedTask = JSON.parse(resultText);

    // Save AI usage log
    if (parsedTask) {
      await prisma.aiUsageLog.create({
        data: {
          userName: userName || "Unknown User",
          userEmail: userEmail || "unknown@domain.com",
          action: "ANSH Copilot Task Generation",
          creditConsumed: 1,
          workspaceId: Number(workspaceId || 1),
        },
      });
    }

    return NextResponse.json({
      success: true,
      task: parsedTask,
    });
  } catch (error: any) {
    console.error("Copilot API Route Error:", error);
    return NextResponse.json(
      {
        success: false,
        error: "An internal server error occurred while processing your request.",
      },
      { status: 500 }
    );
  }
}
